// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFiles(arg1) {
  return window['go']['wails']['App']['ListFiles'](arg1);
}

export function ListTables(arg1) {
  return window['go']['wails']['App']['ListTables'](arg1);
}

export function OpenDatabase() {
  return window['go']['wails']['App']['OpenDatabase']();
}

export function OpenFile(arg1) {
  return window['go']['wails']['App']['OpenFile'](arg1);
}

export function Query(arg1) {
  return window['go']['wails']['App']['Query'](arg1);
}
